#!/bin/bash

engine="https://google.com/search?q=%s"
protocol='^(https?|ftps?|mailto|about|file):///?'

input=$1
checkurl() {
	[ ${#input} -lt 4 ] && return 1
	echo "$input" | grep -Z ' ' && return 1
	echo "$input" | grep -EiZ "$protocol" && return 0
	echo "$input" | grep -FZ '..' && return 1
	prepath=$(echo "$input" | sed 's/(\/|#|\?).*//')
	echo "$prepath" |  grep -FvZ '.' && return 1
	echo "$prepath" |  grep -EZ '^([[:alnum:]~_:-]+\.?){1,3}' && return 0
}

if checkurl
then
    echo "$input" | grep -EivZ "$protocol" && input="https://$input"
else
    input=$(echo "$engine" | sed "s/%s/${input% 0a}/;s/[[:space:]]/+/g")
fi

$BROWSER "$input"
